#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$REPO_ROOT"

echo "┌──────────────────────────────────────────────────────┐"
echo "│  SDP Monorepo — Dev Environment Setup                │"
echo "└──────────────────────────────────────────────────────┘"
echo ""

# ─── Prerequisites ─────────────────────────────────────────────────────

MISSING=""

if ! command -v node &>/dev/null; then
  MISSING="$MISSING\n  • Node.js ≥ 22 — install via nvm (https://nvm.sh)"
fi

if ! command -v go &>/dev/null; then
  MISSING="$MISSING\n  • Go ≥ 1.25"
fi

if ! command -v openssl &>/dev/null; then
  MISSING="$MISSING\n  • openssl (usually pre-installed on Linux / macOS)"
fi

if [ -n "$MISSING" ]; then
  echo "❌ Missing prerequisites:$MISSING"
  echo ""
  exit 1
fi
echo "✅  Node.js $(node --version) — found"
echo "✅  Go $(go version | grep -oE 'go[0-9]+\.[0-9]+') — found"

# ─── Install yarn if missing ───────────────────────────────────────────

if ! command -v yarn &>/dev/null; then
  echo ""
  echo "📦 yarn not found — installing via npm..."
  npm install -g yarn
  echo "✅  yarn $(yarn --version) — installed"
else
  echo "✅  yarn $(yarn --version) — found"
fi

# ─── Install frontend dependencies ─────────────────────────────────────

echo ""
echo "📦 Installing frontend dependencies..."
cd "$REPO_ROOT/frontend"
yarn install --frozen-lockfile 2>/dev/null || yarn install
cd "$REPO_ROOT"
echo "✅  Frontend dependencies installed"

# ─── Check existing .env ───────────────────────────────────────────────

ENV_FILE="$REPO_ROOT/.env"

if [ -f "$ENV_FILE" ]; then
  echo ""
  echo "⚠️   .env already exists — skipping generation."
  echo "    Delete or rename it to regenerate:  rm $ENV_FILE && make dev-setup"
  echo ""
  exit 0
fi

# ─── Generate EC256 private key ────────────────────────────────────────
# NOTE: PEM newlines are replaced with literal \n so godotenv reads the
# whole key as a single value.  The backend's SetConfigOptionEC256PrivateKey
# reverses this with strings.ReplaceAll(key, "\\n", "\n").
echo ""
echo "🔑 Generating EC256 private key (prime256v1)..."
EC256_KEY=$(openssl ecparam -genkey -name prime256v1 -noout 2>/dev/null | \
  awk '{printf "%s\\n", $0}' | sed 's/\\n$//')
echo "✅  EC256 key generated"

# ─── Generate random secrets ────────────────────────────────────────────

SEP24_JWT_SECRET=$(openssl rand -base64 32)

ADMIN_ACCOUNT="dev-admin-$(openssl rand -hex 4)"
ADMIN_API_KEY=$(openssl rand -base64 24)

# ─── Generate Stellar keypairs (SEP10 + Distribution) ─────────────────

echo "🔑 Generating Stellar keypairs..."
cd "$REPO_ROOT/backend"

SEP10_OUTPUT=$(go run tools/generate-dev-keys.go 2>/dev/null)
SEP10_PUBLIC=$(echo "$SEP10_OUTPUT" | grep SEP10_SIGNING_PUBLIC_KEY | cut -d= -f2-)
SEP10_PRIVATE=$(echo "$SEP10_OUTPUT" | grep SEP10_SIGNING_PRIVATE_KEY | cut -d= -f2-)
DIST_PUBLIC=$(echo "$SEP10_OUTPUT" | grep DISTRIBUTION_PUBLIC_KEY | cut -d= -f2-)
DIST_SEED=$(echo "$SEP10_OUTPUT" | grep DISTRIBUTION_SEED | cut -d= -f2-)

cd "$REPO_ROOT"
echo "✅  Stellar keypairs generated"

# ─── Make initial git commit so git commands work ──────────────────────

if ! git rev-parse --short HEAD &>/dev/null; then
  echo ""
  echo "📝 Making initial commit so git-info script works..."
  git add -A
  git commit -m "Initial monorepo setup" --allow-empty
  echo "✅  Initial commit created"
fi

# ─── Create .env ────────────────────────────────────────────────────────

cat > "$ENV_FILE" << EOF
# =============================================================================
# Stellar Disbursement Platform — Development Configuration
# Auto-generated by scripts/dev-setup.sh — edit as needed
# =============================================================================

# ─── Database ───────────────────────────────────────────────────────────────
DATABASE_URL=postgres://sdp:sdp@localhost:5432/sdp?sslmode=disable

# ─── Backend Server ─────────────────────────────────────────────────────────
PORT=8000
BASE_URL=http://localhost:8000
SDP_UI_BASE_URL=http://localhost:3000
CORS_ALLOWED_ORIGINS=http://localhost:3000
INSTANCE_NAME=SDP Dev

# ─── Authentication ────────────────────────────────────────────────────────
EC256_PRIVATE_KEY=${EC256_KEY}
SEP24_JWT_SECRET=${SEP24_JWT_SECRET}
SEP10_SIGNING_PUBLIC_KEY=${SEP10_PUBLIC}
SEP10_SIGNING_PRIVATE_KEY=${SEP10_PRIVATE}
NETWORK_PASSPHRASE=Test SDF Network ; September 2015

# ─── Distribution Account ─────────────────────────────────────────────────
DISTRIBUTION_PUBLIC_KEY=${DIST_PUBLIC}
DISTRIBUTION_SEED=${DIST_SEED}
DISTRIBUTION_ACCOUNT_ENCRYPTION_PASSPHRASE=${DIST_SEED}
CHANNEL_ACCOUNT_ENCRYPTION_PASSPHRASE=${DIST_SEED}

# ─── Multi-tenancy ─────────────────────────────────────────────────────────
SINGLE_TENANT_MODE=true

# ─── reCAPTCHA (disabled for dev) ──────────────────────────────────────────
DISABLE_RECAPTCHA=true

# ─── MFA ────────────────────────────────────────────────────────────────────
DISABLE_MFA=true

# ─── Circle API ─────────────────────────────────────────────────────────────
CIRCLE_API_TYPE=TRANSFERS

# ─── Default Tenant (first admin user) ────────────────────────────────────
DEFAULT_TENANT_OWNER_EMAIL=default@default.local
DEFAULT_TENANT_OWNER_FIRST_NAME=Default
DEFAULT_TENANT_OWNER_LAST_NAME=Owner
DEFAULT_TENANT_DISTRIBUTION_ACCOUNT_TYPE=DISTRIBUTION_ACCOUNT.STELLAR.ENV

# ─── Admin API ──────────────────────────────────────────────────────────────
ADMIN_PORT=8003
ADMIN_ACCOUNT=${ADMIN_ACCOUNT}
ADMIN_API_KEY=${ADMIN_API_KEY}

# ─── Metrics ────────────────────────────────────────────────────────────────
METRICS_PORT=8002
METRICS_TYPE=PROMETHEUS

# ─── Messaging (dry-run for dev — no real SMS/email sent) ───────────────────
SMS_SENDER_TYPE=DRY_RUN
EMAIL_SENDER_TYPE=DRY_RUN

# ─── Frontend (REACT_APP_* vars are injected at build time via Vite) ──────
REACT_APP_API_URL=http://localhost:8000
REACT_APP_SINGLE_TENANT_MODE=true
REACT_APP_RECAPTCHA_SITE_KEY=
REACT_APP_STELLAR_EXPERT_URL=https://stellar.expert/explorer/testnet
REACT_APP_HORIZON_URL=https://horizon-testnet.stellar.org
REACT_APP_RPC_ENABLED=false
EOF

echo "✅  .env created at $ENV_FILE"

# ─── Create frontend runtime env config ────────────────────────────────
# The frontend fetches /settings/env-config.js at startup to get runtime
# configuration. In production this is generated at deploy time. For dev
# we create it with matching values.
echo ""
echo "🔧 Creating frontend runtime env config..."
mkdir -p "$REPO_ROOT/frontend/public/settings"

cat > "$REPO_ROOT/frontend/public/settings/env-config.js" << 'EOF'
window._env_ = {
  API_URL: "http://localhost:8000",
  DISABLE_TENANT_PREFIL_FROM_DOMAIN: "",
  STELLAR_EXPERT_URL: "https://stellar.expert/explorer/testnet",
  HORIZON_URL: "https://horizon-testnet.stellar.org",
  RPC_ENABLED: false,
  RECAPTCHA_SITE_KEY: "",
  SINGLE_TENANT_MODE: true,
};
EOF

echo "✅  Frontend runtime env config created"
echo ""
echo "┌──────────────────────────────────────────────────────┐"
echo "│  Next:  make dev                                     │"
echo "│        or  make docker-compose-up                    │"
echo "└──────────────────────────────────────────────────────┘"
